### ISSUE TITLE
23017 library

### ISSUE THREAD

**Issue by thufer2002** [fourstix/Elfos-I2C-Libraries#5]
[mcp23017.zip](https://github.com/fourstix/Elfos-I2C-Libraries/files/13338834/mcp23017.zip)

   Attached is a zip file of my completed library. I’ve used your format and conventions as best I can to make it easy for you to evaluate, use, publish.  Though I put Copyright and my name feel free to remove and use yours if you feel this library is worth publishing as is or with changes, totally up to you. 
 
I know the chip supports interrupts but I did not write any specific functions for that, though I think there’s enough here to support them.  My thinking is that the typical use of i2c is that devices are at the end of a wire not on an embedded board connected directly to the 1802.
 
I have plans to try and support the following 3 devices as well with their own libraries:
blinkM – smart Led
pcf8591 –i2c expansion chip with 4 analog inputs w 8 bit A to D
tls2561 – Adafruit LUX sensor
 
I develop on a Mac in a Docker Container running Linux.  As such my bat files are cmds for linux not windows change as needed. My directory structure looks like:
/--Include (includes and defs in this folder)
/--Lib
     |---mcp23017-lib (folder with source, bats, and finished lib)
     |---mcp23017.lib (finished lib)
/--src
     |--- mcp23017-projects
 
If you have time I’d like feedback on style, code correctness or efficiency, documentation, etc. to help me improve. To me this is all about the learning so feedback welcomed !

Cheers and thanks again for all your hard work on keeping the 1802 alive.

**Comment by fourstix** [comment]
Great, Thank you!  I will definitely check it out.

**Comment by fourstix** [comment]
Hi Nick,
Thanks for this contribution and all the others!  I've added them all to the code in the main branch under the directory "/nick/" .
