### ISSUE TITLE
BlinkM code

### ISSUE THREAD

**Issue by thufer2002** [fourstix/Elfos-I2C-Libraries#6]
Another library, again based off all your hard work. Let me know if any good or if I should stop sending. This supports only the BlinkM thing, not the mini or max devices. Attached is the zip file and a picture of my mini with 8 different devices attached.

Cheers
Nick
KN6OUU

[BlinkM.zip](https://github.com/fourstix/Elfos-I2C-Libraries/files/13358729/BlinkM.zip)
![IMG_0872](https://github.com/fourstix/Elfos-I2C-Libraries/assets/19767361/498663e8-2057-4cb5-8ecb-af93266d86e9)

**Comment by fourstix** [comment]
Hi Nick,
Nice picture! Thanks for this contribution!  I've added it to the code in the main branch under the directory "/nick/" with all the others.
